import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, describe, expect, it } from "vitest";

import type { TestPlan, ValidationResult } from "../model/schemas.js";
import { emitFailureGherkin } from "./failure-gherkin.js";

let tempDirs: string[] = [];

afterEach(() => {
  for (const dir of tempDirs) {
    rmSync(dir, { recursive: true, force: true });
  }
  tempDirs = [];
});

function makeCorpusDir(): string {
  const dir = mkdtempSync(join(tmpdir(), "failure-gherkin-test-"));
  tempDirs.push(dir);
  return dir;
}

const MODEL_VERSION =
  "fab621435d1cbcad3cd10e730f56decf9fc62bc7e50648fb27b100b25348da7d";

const plan: TestPlan = {
  planId: "smoke",
  modelVersion: MODEL_VERSION,
  scenarios: [],
};

function failing(overrides: Partial<ValidationResult>): ValidationResult {
  return {
    contractId: "portfolio-value-shown",
    passed: false,
    details: 'expected "value shown" ≥ 1 but observed 0',
    corpusRefs: ["snapshot:post", "probe:selected-view"],
    ...overrides,
  };
}

function passing(): ValidationResult {
  return {
    contractId: "portfolio-value-shown",
    passed: true,
    corpusRefs: ["snapshot:post"],
  };
}

function readFeature(corpusDir: string, runId: string): string {
  return readFileSync(join(corpusDir, runId, "failure.feature"), "utf8");
}

describe("emitFailureGherkin", () => {
  it("writes failure.feature under the run dir naming the contract, plan, model version, and refs (FAILED_SINGLE)", () => {
    const corpusDir = makeCorpusDir();
    const runId = "2026-09-01T10:00:00Z";

    const written = emitFailureGherkin({
      corpusDir,
      runId,
      plan,
      results: [failing({})],
    });

    expect(written).toEqual([`${runId}/failure.feature`]);
    const featurePath = join(corpusDir, runId, "failure.feature");
    expect(existsSync(featurePath)).toBe(true);

    const content = readFeature(corpusDir, runId);
    expect(content).toContain("# Derived artifact — generated by the reporter. Never the source of truth.");
    expect(content).toContain("@run:2026-09-01T10:00:00Z");
    expect(content).toContain(
      'Feature: Failed verification — plan "smoke" (model fab62143…) run 2026-09-01T10:00:00Z',
    );
    expect(content).toContain('Scenario: contract "portfolio-value-shown" was violated');
    expect(content).toContain('Given a recorded corpus run "2026-09-01T10:00:00Z" for plan "smoke"');
    expect(content).toContain(
      'And the validator reported: expected "value shown" ≥ 1 but observed 0',
    );
    expect(content).toContain("And the recorded evidence it ran against is:");
    expect(content).toContain("| snapshot:post |");
    expect(content).toContain("| probe:selected-view |");
  });

  it("renders scenarios in stable sorted order regardless of arrival order (MULTI_FAIL)", () => {
    const corpusDir = makeCorpusDir();
    const runId = "run-multi";

    const alpha = failing({ contractId: "alphaContract", details: "boom alpha", corpusRefs: ["snapshot:post"] });
    const beta = failing({ contractId: "betaContract", details: "boom beta", corpusRefs: ["snapshot:post", "snapshot:pre"] });
    const gamma = failing({ contractId: "gammaContract", details: "boom gamma", corpusRefs: ["snapshot:post"] });

    emitFailureGherkin({
      corpusDir,
      runId,
      plan,
      results: [gamma, alpha, beta],
    });
    const content = readFeature(corpusDir, runId);

    const alphaAt = content.indexOf('Scenario: contract "alphaContract"');
    const betaAt = content.indexOf('Scenario: contract "betaContract"');
    const gammaAt = content.indexOf('Scenario: contract "gammaContract"');

    expect(alphaAt).toBeGreaterThanOrEqual(0);
    expect(betaAt).toBeGreaterThan(alphaAt);
    expect(gammaAt).toBeGreaterThan(betaAt);
  });

  it("is deterministic: arbitrary arrival order yields byte-identical output (NFR-1)", () => {
    const corpusDir = makeCorpusDir();
    const runId = "run-det";

    const a = failing({ contractId: "aContract", details: "boom a" });
    const b = failing({ contractId: "bContract", details: "boom b" });

    emitFailureGherkin({ corpusDir, runId, plan, results: [b, a] });
    const first = readFeature(corpusDir, runId);

    // Same inputs, different arrival order → identical bytes.
    const otherDir = makeCorpusDir();
    emitFailureGherkin({ corpusDir: otherDir, runId, plan, results: [a, b] });
    const second = readFeature(otherDir, runId);

    expect(second).toBe(first);
  });

  it("writes nothing and returns [] when all results pass (PASS_ONLY)", () => {
    const corpusDir = makeCorpusDir();

    const written = emitFailureGherkin({
      corpusDir,
      runId: "run-green",
      plan,
      results: [passing(), passing()],
    });

    expect(written).toEqual([]);
    expect(existsSync(join(corpusDir, "run-green", "failure.feature"))).toBe(false);
    expect(existsSync(join(corpusDir, "run-green"))).toBe(false);
  });

  it("writes nothing and returns [] for an empty result set (EMPTY)", () => {
    const corpusDir = makeCorpusDir();

    expect(() =>
      emitFailureGherkin({ corpusDir, runId: "run-empty", plan, results: [] }),
    ).not.toThrow();
    const written = emitFailureGherkin({ corpusDir, runId: "run-empty", plan, results: [] });

    expect(written).toEqual([]);
    expect(existsSync(join(corpusDir, "run-empty", "failure.feature"))).toBe(false);
  });

  it("omits only the evidence clause for a failing result with empty corpusRefs (NO_CORPUS_REF)", () => {
    const corpusDir = makeCorpusDir();
    const runId = "run-norefs";

    emitFailureGherkin({
      corpusDir,
      runId,
      plan,
      results: [failing({ corpusRefs: [], details: "boom" })],
    });

    const content = readFeature(corpusDir, runId);
    expect(content).toContain('Scenario: contract "portfolio-value-shown" was violated');
    expect(content).toContain("@run:run-norefs");
    expect(content).toContain('Feature: Failed verification — plan "smoke"');
    expect(content).toContain("And the validator reported: boom");
    expect(content).not.toContain("And the recorded evidence it ran against is:");
  });

  it("omits only the validator-reported clause when details is absent, keeping the evidence table (NO_DETAILS)", () => {
    const corpusDir = makeCorpusDir();
    const runId = "run-nodetails";

    emitFailureGherkin({
      corpusDir,
      runId,
      plan,
      results: [failing({ details: undefined })],
    });

    const content = readFeature(corpusDir, runId);
    expect(content).toContain('Scenario: contract "portfolio-value-shown" was violated');
    expect(content).not.toContain("And the validator reported:");
    expect(content).toContain("And the recorded evidence it ran against is:");
    expect(content).toContain("| snapshot:post |");
  });

  it("sanitizes line breaks in details so the reported clause stays a single Gherkin step", () => {
    const corpusDir = makeCorpusDir();
    const runId = "run-multiline-details";

    emitFailureGherkin({
      corpusDir,
      runId,
      plan,
      results: [failing({ details: "line one\r\nline two\nline three" })],
    });

    const content = readFeature(corpusDir, runId);
    expect(content).toContain("And the validator reported: line one line two line three");
    expect(content).not.toContain("\n\n    And the validator reported:");
    // No embedded line break in the rendered clause: the reported line is intact.
    const reportedLine = content
      .split("\n")
      .find((line) => line.includes("And the validator reported:"));
    expect(reportedLine).toBe("    And the validator reported: line one line two line three");
  });

  it("escapes a literal | in a corpusRef as \\| in the evidence table", () => {
    const corpusDir = makeCorpusDir();
    const runId = "run-pipe-ref";

    emitFailureGherkin({
      corpusDir,
      runId,
      plan,
      results: [failing({ corpusRefs: ["snapshot:post", "probe:selected-view|header"] })],
    });

    const content = readFeature(corpusDir, runId);
    expect(content).toContain("And the recorded evidence it ran against is:");
    expect(content).toContain("| snapshot:post |");
    expect(content).toContain("| probe:selected-view\\|header |");
  });

  it("creates the run dir recursively when it does not exist (MISSING_RUN_DIR)", () => {
    const corpusDir = makeCorpusDir();
    const runId = "run-created";

    expect(existsSync(join(corpusDir, runId))).toBe(false);

    emitFailureGherkin({
      corpusDir,
      runId,
      plan,
      results: [failing({})],
    });

    expect(existsSync(join(corpusDir, runId))).toBe(true);
    expect(existsSync(join(corpusDir, runId, "failure.feature"))).toBe(true);
  });

  it("re-emits byte-identical content, overwriting in place (RE_EMIT)", () => {
    const corpusDir = makeCorpusDir();
    const runId = "run-reemit";

    emitFailureGherkin({ corpusDir, runId, plan, results: [failing({})] });
    const first = readFeature(corpusDir, runId);

    emitFailureGherkin({ corpusDir, runId, plan, results: [failing({})] });
    const second = readFeature(corpusDir, runId);

    expect(second).toBe(first);
  });
});
