// Failure reporter (Story 3.4) — renders failing ValidationResults into a
// reviewable Gherkin artifact at `{corpusDir}/{runId}/failure.feature`, so a
// QE can read a failure and a PM/PO can adjudicate it (FR-7).
//
// Pure + deterministic (NFR-1): same corpus + same results → byte-identical
// artifact; no browser, no network, no AI in the loop. The only side effect is
// writing the derived file. The emitter consumes only `ValidationResult` +
// `TestPlan` and never touches authored `features/*.feature` files — this
// artifact is a derived, regenerable view, never the source of truth (AD-9,
// Story 3.6).

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import type { TestPlan, ValidationResult } from "../model/schemas.js";

/** Inputs to `emitFailureGherkin`. */
export interface EmitFailureGherkinInput {
  /** Absolute path to the corpus output directory. */
  corpusDir: string;
  /** Run-id of the recorded corpus run the results were produced against. */
  runId: string;
  /** The test plan the run executed (names plan id + model version). */
  plan: TestPlan;
  /** Validator results for the run — passing results are filtered out. */
  results: ValidationResult[];
}

/** The derived-artifact header marking the file as regenerable, never SSOT. */
const DERIVED_HEADER = [
  "# Derived artifact — generated by the reporter. Never the source of truth.",
  "# Regenerate by re-running verification; do not hand-edit (Story 3.6).",
];

/**
 * Render the failing results of one corpus run into a reviewable Gherkin
 * artifact at `{corpusDir}/{runId}/failure.feature` (Story 3.4, FR-7).
 *
 * Failing results are sorted by a stable key so the emitted bytes never depend
 * on the order the results arrived in (NFR-1). An all-green or empty result
 * set writes nothing and returns an empty path list. The run dir is created
 * recursively on write, mirroring `finishRun`.
 *
 * @returns the corpus-relative paths written (always at most one entry) or `[]`
 *   when nothing failed.
 */
export function emitFailureGherkin({
  corpusDir,
  runId,
  plan,
  results,
}: EmitFailureGherkinInput): string[] {
  const failures = results.filter((result) => !result.passed);
  if (failures.length === 0) {
    return [];
  }

  const content = renderFailureFeature(runId, plan, failures);
  const relPath = `${runId}/failure.feature`;
  mkdirSync(join(corpusDir, runId), { recursive: true });
  writeFileSync(join(corpusDir, relPath), content);

  return [relPath];
}

/** Stable sort key: contractId, then the joined corpusRefs, then the detail
 * message — output bytes never depend on arrival order (NFR-1). */
function sortKey(result: ValidationResult): string {
  return `${result.contractId}\u0000${result.corpusRefs.join("\u0000")}\u0000${result.details ?? ""}`;
}

function compareResults(a: ValidationResult, b: ValidationResult): number {
  const ka = sortKey(a);
  const kb = sortKey(b);
  return ka < kb ? -1 : ka > kb ? 1 : 0;
}

/** Collapse any line break in a `details` message to a single space so the
 * "validator reported" clause stays a single Gherkin step (P1 sanitization).
 * Everything else — including quotes — is kept verbatim. */
function toSingleLine(value: string): string {
  return value.replace(/\r\n|\r|\n/g, " ");
}

/** Escape a literal `|` in a corpusRef so the evidence table stays a valid
 * pipe table (Gherkin table cell escaping, P2). */
function escapeTableCell(value: string): string {
  return value.replace(/\|/g, "\\|");
}

/**
 * Build the `.feature` text for a set of failing results. One Scenario per
 * failure, naming the failing contract, the plan id + model version, and the
 * corpus refs it ran against. `details` and `corpusRefs` are rendered verbatim
 * except for structure-breaking characters sanitized at the cell/step boundary:
 * line breaks in `details` collapse to a single space so the "validator
 * reported" clause stays one Gherkin step, and a literal `|` in a corpusRef is
 * escaped as `\|` so the evidence table stays a valid pipe table. A missing
 * `details` drops only the "validator reported" clause, empty `corpusRefs`
 * drops only the evidence table (the corpus stays named through the `@run:`
 * tag and the Feature plan line).
 */
function renderFailureFeature(
  runId: string,
  plan: TestPlan,
  failures: ValidationResult[],
): string {
  const lines: string[] = [...DERIVED_HEADER];

  lines.push(`@run:${runId}`);
  lines.push(
    `Feature: Failed verification — plan "${plan.planId}" (model ${plan.modelVersion.slice(0, 8)}…) run ${runId}`,
  );
  lines.push("");

  for (const failure of [...failures].sort(compareResults)) {
    lines.push(`  Scenario: contract "${failure.contractId}" was violated`);
    lines.push(`    Given a recorded corpus run "${runId}" for plan "${plan.planId}"`);
    lines.push(`    When the shared validator for contract "${failure.contractId}" ran over the corpus`);
    lines.push(`    Then the validation failed`);
    if (failure.details !== undefined) {
      lines.push(`    And the validator reported: ${toSingleLine(failure.details)}`);
    }
    if (failure.corpusRefs.length > 0) {
      lines.push(`    And the recorded evidence it ran against is:`);
      for (const ref of failure.corpusRefs) {
        lines.push(`      | ${escapeTableCell(ref)} |`);
      }
    }
    lines.push("");
  }

  while (lines.length > 0 && lines[lines.length - 1] === "") {
    lines.pop();
  }
  return `${lines.join("\n")}\n`;
}
