// repro-generator.ts — turns a reported bug path (a sequence of FSM states and
// contracts) into a standalone `scripts/repro-<slug>.ts` that a developer runs
// without reasoning about the testware runtime machinery. The emitted script's
// only testware dependencies are playwright, the model, and the action-map — it
// never imports the Orchestrator, Validator, validators, or collectors (FR-12a,
// AD-7). It drives each step via the live action-map so a regenerated repro
// always reflects the current spec; an unmodeled path is reported as a gap,
// never silently approximated (FR-12c).

import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

import { homePageModel } from "../model/fsm.js";
import { allContracts } from "../model/contracts.js";
import { actionMap } from "../orchestrator/action-map.js";
import type { ScenarioStep } from "../model/schemas.js";

/** Input to repro generation: the reported bug path plus run-time config. */
export interface ReproPath {
  /** Kebab-case slug used to name the emitted script. */
  slug: string;
  /** Base URL of the app under test (mirrors run-smoke.ts). */
  baseUrl: string;
  /** CSS selector waited for after initial navigation. */
  readySelector: string;
  /** CSS selector waited for after each step action; defaults to `readySelector`. */
  settleSelector?: string;
  /** CDP endpoint to attach to an already-authenticated browser. */
  cdpUrl?: string;
  /** Ordered FSM steps the repro executes, in sequence. */
  steps: ScenarioStep[];
}

/** Default CDP endpoint for attaching to an already-authenticated browser. */
const DEFAULT_CDP_URL = "http://127.0.0.1:9222";

/** Per-step timeout baked into the emitted script (mirrors run-smoke.ts). */
const STEP_TIMEOUT_MS = 10_000;

/** Directory (repo-relative) the emitted repros are written into. */
const SCRIPTS_DIR = "scripts";

/**
 * Validate `path` against the Model + action-map and return the source of
 * `scripts/repro-<slug>.ts`. Throws a gap naming the offending step on an
 * empty or unresolvable path — never an approximated path (FR-12c).
 * Deterministic (NFR-1): identical inputs → identical output.
 */
export function generateReproScript(path: ReproPath): string {
  if (path.steps.length === 0) {
    throw new Error("gap: repro path is empty (no steps)");
  }
  validateSlug(path.slug);
  validatePath(path.steps);

  if (!path.baseUrl || !path.readySelector) {
    throw new Error(
      "gap: repro run config is missing a non-empty baseUrl or readySelector",
    );
  }

  const cdpUrl = path.cdpUrl || DEFAULT_CDP_URL;
  const settleSelector = path.settleSelector || path.readySelector;
  const stepsJson = JSON.stringify(path.steps);

  return [
    "// Standalone repro for a reported bug path (Story 4.1).",
    "// Generated by repro-generator.ts from the Model + the action-map.",
    "// Drives each step via the live action-map, so a regenerated repro always",
    "// reflects the current spec (a later action-map edit is picked up at run time).",
    "// Only testware deps: playwright + model + action-map. No runtime machinery, no",
    "// runner, no validators, no collectors.",
    "// Run with:  npx tsx scripts/repro-" + path.slug + ".ts",
    "",
    'import { chromium } from "playwright";',
    'import { actionMap } from "../orchestrator/action-map.js";',
    'import { homePageModel } from "../model/fsm.js";',
    "",
    `const CDP_URL = ${JSON.stringify(cdpUrl)};`,
    `const BASE_URL = ${JSON.stringify(path.baseUrl)};`,
    `const READY_SELECTOR = ${JSON.stringify(path.readySelector)};`,
    `const SETTLE_SELECTOR = ${JSON.stringify(settleSelector)};`,
    `const STEP_TIMEOUT_MS = ${STEP_TIMEOUT_MS};`,
    `const STEPS: Array<{ stateId: string; contractId: string }> = ${stepsJson};`,
    "",
    "async function main(): Promise<void> {",
    "  // Self-contained CDP attach (no runtime browser module): connect to an",
    "  // already-authenticated Chromium, require exactly one authenticated context,",
    "  // open a fresh tab, and navigate to the app. The human browser is never closed.",
    "  const browser = await chromium.connectOverCDP(CDP_URL);",
    "  try {",
    "    const contexts = browser.contexts();",
    "    if (contexts.length !== 1) {",
    "      throw new Error(",
    "        `CDP endpoint ${CDP_URL} exposes ${contexts.length} contexts - expected exactly one authenticated context. ` +",
    "        `Open a Kraken Pro tab in the attached browser and re-run.`,",
    "      );",
    "    }",
    "    const page = await contexts[0].newPage();",
    "    try {",
    "      await page.goto(BASE_URL);",
    "      await page.waitForSelector(READY_SELECTOR, { timeout: STEP_TIMEOUT_MS });",
    "",
    "      // Read the CURRENT model at run time: a state or transition that a later",
    "      // spec edit retired is caught loudly here rather than silently running a",
    "      // stale path (FR-12c).",
    "      const stateIds = new Set(homePageModel.states.map((s) => s.stateId));",
    "      const transitionKeys = new Set(",
    "        homePageModel.transitions.map((t) => `${t.from}\\u0000${t.contractId}`),",
    "      );",
    "      for (const [i, step] of STEPS.entries()) {",
    "        const where = `step ${i + 1} (${step.stateId} -> ${step.contractId})`;",
    "        if (!stateIds.has(step.stateId)) {",
    "          throw new Error(",
    "            `state \"${step.stateId}\" no longer exists in the current model (${where})`,",
    "          );",
    "        }",
    "        if (!transitionKeys.has(`${step.stateId}\\u0000${step.contractId}`)) {",
    "          throw new Error(",
    "            `transition \"${step.contractId}\" from state \"${step.stateId}\" is no longer in the current model (${where})`,",
    "          );",
    "        }",
    "        const action = actionMap[step.contractId];",
    "        if (!action) {",
    "          throw new Error(",
    "            `no action for contract \"${step.contractId}\" in the current action-map (${where})`,",
    "          );",
    "        }",
    "        try {",
    "          await action({ page });",
    "          await page.waitForSelector(SETTLE_SELECTOR, { timeout: STEP_TIMEOUT_MS });",
    "        } catch (err) {",
    "          throw new Error(",
    "            `${where} failed: ${err instanceof Error ? err.message : String(err)}`,",
    "          );",
    "        }",
    "      }",
    "    } finally {",
    "      // Close the run's own tab even on failure, so a failed repro never leaves a",
    "      // stray tab behind in the human's authenticated context (browser.ts's pattern).",
    "      try {",
    "        await page.close();",
    "      } catch {",
    "        // Already closed.",
    "      }",
    "    }",
    "  } finally {",
    "    // Close = disconnect over CDP; the authenticated browser stays open.",
    "    await browser.close();",
    "  }",
    "}",
    "",
    "main().catch((err) => {",
    "  console.error(err instanceof Error ? err.message : String(err));",
    "  process.exitCode = 1;",
    "});",
    "",
  ].join("\n");
}

/**
 * Write `scripts/repro-<slug>.ts` for `path` and return its repo-relative path.
 * Validates before writing — a gap writes nothing (FR-12c).
 */
export async function writeReproScript(path: ReproPath): Promise<string> {
  const source = generateReproScript(path);
  const filePath = join(SCRIPTS_DIR, `repro-${path.slug}.ts`);
  await mkdir(SCRIPTS_DIR, { recursive: true });
  await writeFile(filePath, source, "utf8");
  return filePath;
}

/**
 * Reject a slug that could escape `scripts/` or produce no meaningful file.
 */
function validateSlug(slug: string): void {
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) {
    throw new Error(
      `gap: repro slug "${slug}" is not a safe kebab-case filename (lowercase letters, digits, hyphens)`,
    );
  }
}

/**
 * Resolve every step against the Model (states + contracts + transitions) and the
 * action-map, mirroring the ssot-guard rules so a gap never yields a partial repro.
 */
function validatePath(steps: ScenarioStep[]): void {
  const stateIds = new Set(homePageModel.states.map((s) => s.stateId));
  const contractIds = new Set(allContracts.map((c) => c.contractId));
  const transitionKeys = new Set(
    homePageModel.transitions.map((t) => `${t.from}\u0000${t.contractId}`),
  );

  for (const [i, step] of steps.entries()) {
    const where = `step ${i + 1} (${step.stateId} -> ${step.contractId})`;

    if (!step.stateId) {
      throw new Error(`gap: ${where} has an empty stateId`);
    }
    if (!stateIds.has(step.stateId)) {
      throw new Error(`gap: ${where} references unknown state "${step.stateId}"`);
    }

    if (!step.contractId) {
      throw new Error(`gap: ${where} has an empty contractId`);
    }
    if (!contractIds.has(step.contractId)) {
      throw new Error(`gap: ${where} references unknown contract "${step.contractId}"`);
    }
    if (!(step.contractId in actionMap)) {
      throw new Error(
        `gap: ${where} references contract "${step.contractId}" missing from the action-map`,
      );
    }

    const key = `${step.stateId}\u0000${step.contractId}`;
    if (!transitionKeys.has(key)) {
      throw new Error(
        `gap: ${where} - no transition from state "${step.stateId}" driven by contract "${step.contractId}"`,
      );
    }
  }
}